In [198]:
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np
import scipy
import pandas as pd
from scipy.stats import chisquare
from scipy import stats

%matplotlib inline

In [2]:
from statsmodels.stats.weightstats import _zconfint_generic, _tconfint_generic
from statsmodels.stats.proportion import proportion_confint
from statsmodels.stats.proportion import samplesize_confint_proportion

In [4]:
def proportions_confint_diff_ind(p1_count, p2_count, len_p1, len_p2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)
    
    p1 = float(p1_count) / len_p1
    p2 = float(p2_count) / len_p2
    
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ len_p1 + p2 * (1 - p2)/ len_p2)
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ len_p1 + p2 * (1 - p2)/ len_p2)
    
    return (left_boundary, right_boundary)

In [139]:
proportion_confint(67, 100, method = 'normal',alpha=0.088875)

(0.58999978691237331, 0.75000021308762677)

In [196]:
proportion_confint(67, 100, method = 'wilson',alpha=0.064672)

(0.57877783027574903, 0.74999991555273471)

In [199]:
stats.binom_test(67, 100, .75, alternative = 'two-sided')

0.082222588913866079

In [40]:
df = pd.read_csv('pines.txt', sep='\t')
df.sn = df.sn.astype(float)
df.we = df.we.astype(float)

In [53]:
data = np.zeros((5,5))
for r in df.values:
    ri = int(np.floor(r[0]/40))
    if ri==5:
        ri = 4
    rj = int(np.floor(r[1]/40))
    if rj==5:
        rj = 4
    data[ri,rj]+=1

In [54]:
data

array([[ 18.,  26.,  29.,  25.,  20.],
       [ 14.,  12.,  22.,  34.,  25.],
       [ 12.,  24.,  15.,  50.,  37.],
       [  8.,  19.,  31.,  50.,   7.],
       [  7.,   8.,  37.,  27.,  27.]])

In [55]:
scipy.stats.binned_statistic_2d(df.sn, df.we, None, 'count', bins=5)[0]

array([[ 18.,  26.,  29.,  25.,  20.],
       [ 14.,  12.,  22.,  34.,  25.],
       [ 12.,  24.,  15.,  50.,  37.],
       [  8.,  19.,  31.,  50.,   7.],
       [  7.,   8.,  37.,  27.,  27.]])

In [60]:
mean_val = df.shape[0]/25.0

In [61]:
mean_val

23.36

In [62]:
expected = np.full((5,5),mean_val)

In [64]:
expected

array([[ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36]])

In [75]:
data.reshape(25,)

array([ 18.,  26.,  29.,  25.,  20.,  14.,  12.,  22.,  34.,  25.,  12.,
        24.,  15.,  50.,  37.,   8.,  19.,  31.,  50.,   7.,   7.,   8.,
        37.,  27.,  27.])

In [77]:
chisquare(data.reshape(25,), expected.reshape(25,), ddof = 0)

Power_divergenceResult(statistic=150.58904109589042, pvalue=2.5746697749672791e-20)